version: '3.4'

services:
  user-service:
    image: user-service
    build:
      context: ./src
      dockerfile: UserService/Dockerfile
    ports:
      - "5158:5158"

  api-gateway:
    image: api-gateway
    build:
      context: ./src/APIGateway
      dockerfile: Dockerfile
    ports:
      - "7001:7001"

  crash-game-service:
    image: crash-game-service
    build:
      context: ./src
      dockerfile: CrashGameService/Dockerfile
    ports:
      - "7021:7021"

  provider-service:
    image: provider-service
    build:
      context: ./src
      dockerfile: GameProviderService/Dockerfile
    ports:
      - "7189:7189"
