version: '3.4'

services:
  user-service:
    image: user-service
    build:
      context: ./src/UserService
      dockerfile: Dockerfile
    ports:
      - "5159:5158"
    depends_on:
      - api-gateway

  api-gateway:
    image: api-gateway
    build:
      context: ./src/APIGateway
      dockerfile: Dockerfile
    ports:
      - "7002:7001"

  crash-game-service:
    image: crash-game-service
    build:
      context: ./src/CrashGameService
      dockerfile: Dockerfile
    ports:
      - "7022:7021"
    depends_on:
      - api-gateway

  provider-service:
    image: provider-service
    build:
      context: ./src/GameProviderService
      dockerfile: Dockerfile
    ports:
      - "7188:7189"
    depends_on:
      - api-gateway